# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Imaginary
tagline:          Kevin Lin&#39;s Blog
url:              http://sqrtnegative1.github.io
paginate:         1
baseurl:          /
author:
  name:           Kevin Lin
#  url:            https://twitter.com/mdo
  email:          kevinlin@gmail.com

# Custom vars
version:          1.0.0
# github:
#  repo:           https://github.com/poole/poole
